# workflows:
#   my-workflow:
#     name: Codemagic Workflow
#     environment:
#       flutter: stable
#     scripts:
#       - name: Get dependencies
#         script: |
#           flutter packages pub get
#       - name: Flutter analyze
#         script: |
#           flutter analyze
#       - name: Flutter test
#         script: |
#           flutter test
#       - name: Build APK with Flutter
#         script: |
#           flutter build apk --release

#     artifacts:
#       - build/**/outputs/**/*.apk
#       - build/**/outputs/**/*.aab
#       - build/**/outputs/**/mapping.txt
#       - flutter_drive.log
#     publishing:
#       firebase:
#         firebase_token: $FIREBASE_TOKEN
#         android:
#           app_id: 1:651915284618:android:3e97858628e9bf4e1a5d73

workflows:




  android-dev-workflow:
    name: Android Dev Workflow
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build APK (Dev)
        script: |
          flutter build apk \
            --flavor dev \
            --dart-define=appFlavor=dev \
            --build-name=1.0.0 \
            --build-number=1 \
            --release
    artifacts:
      - build/app/outputs/flutter-apk/app-dev-release.apk

  android-prod-workflow:
    name: Android Prod Workflow
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build APK (Prod)
        script: |
          flutter build apk \
            --flavor prod \
            --dart-define=appFlavor=prod \
            --build-name=1.0.0 \
            --build-number=1 \
            --release
    artifacts:
      - build/app/outputs/flutter-apk/app-prod-release.apk

