// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9Hzc9k_y7TySPOkvc6JmQFoAUiHykXNs',
    appId: '1:651915284618:web:5d1073577234ed151a5d73',
    messagingSenderId: '651915284618',
    projectId: 'codemagic-test-49fd7',
    authDomain: 'codemagic-test-49fd7.firebaseapp.com',
    storageBucket: 'codemagic-test-49fd7.firebasestorage.app',
    measurementId: 'G-4W2HFEN3BE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS8jCuX-RcNWaulcUiraNWiCXoiy_9RTU',
    appId: '1:651915284618:android:3e97858628e9bf4e1a5d73',
    messagingSenderId: '651915284618',
    projectId: 'codemagic-test-49fd7',
    storageBucket: 'codemagic-test-49fd7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP_zi_A1hO_9_bzVrjvoz1hcvCGCSf_Pw',
    appId: '1:651915284618:ios:1876135620d06e1e1a5d73',
    messagingSenderId: '651915284618',
    projectId: 'codemagic-test-49fd7',
    storageBucket: 'codemagic-test-49fd7.firebasestorage.app',
    iosBundleId: 'com.example.codemagic',
  );
}
